name: Hello World Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello World! This is a release for tag ${{ github.ref_name }}"
